/***************************************************************************************************
Question 1: Total Revenue by Product Type: Calculate the total revenue generated by each product type. This can help identify the most profitable products.*/ 

use supply_db

With CTE as (
SELECT 
    a1.order_id, 
    a1.type, 
    a1.shipping_mode, 
    a2.sales, 
    a2.item_id, 
    a1.customer_id, 
    a3.product_id, 
    a3.department_id, 
    a3.category_id,
    a4.name
FROM orders AS a1
JOIN ordered_items AS a2
    ON a1.order_id = a2.order_id
JOIN product_info as a3
    ON a2.item_id = a3.product_id
JOIN department as a4
ON a3.department_id = a4.id)

select department_id, sum(sales) as total_sales
from CTE 
GROUP by department_id
ORDER BY total_sales desc;

/*** 

/***************************************************************************************************
Question 2: Total Products Sold by Location: 
Determine the total number of products sold in each location to understand regional demand..*/ 
use supply_db;

With CTE as (
SELECT 
    a1.order_id, 
    a1.type, 
    a1.order_state, 
    a2.sales, 
    a2.item_id, 
    a1.customer_id, 
    a3.product_id, 
    a3.department_id, 
    a3.category_id,
    a4.name
FROM orders AS a1
JOIN ordered_items AS a2
    ON a1.order_id = a2.order_id
JOIN product_info as a3
    ON a2.item_id = a3.product_id
JOIN department as a4
ON a3.department_id = a4.id)

select order_state as state, count(order_id) as Number_of_order, ROUND(sum(SALES),0) AS TOTAL_SALE
from CTE
GROUP BY STATE
ORDER BY TOTAL_SALE DESC

/***************************************************************************************************
Question 3: Shipping Efficient by Shipping Mode: Delayed rate which carrier is the most quanlity-effective.
 --> Top shipping mode efficient*/ 
 
 use supply_db;
 WITH TABLE_01 AS (
WITH CTE AS (
Select *,
CASE 
WHEN ORDER_STATUS IN (' SUSPECTED_FRAUD' , 'CANCELED') THEN 'Cancelled shipment'
WHEN REAL_SHIPPING_DAYS < SCHEDULED_SHIPPING_DAYS THEN 'Within schedule'
WHEN REAL_SHIPPING_DAYS =  SCHEDULED_SHIPPING_DAYS THEN 'On time'
WHEN REAL_SHIPPING_DAYS -  SCHEDULED_SHIPPING_DAYS > 0 THEN 'DELAYED'
ELSE ' Others '
END as  Shipping_status
From orders ) 

SELECT  SHIPPING_MODE,  COUNT(CASE WHEN SHIPPING_STATUS =  'DELAYED' THEN 'DELAYED_SHIPPING' END) AS DELAYED_SHIPPING_MODE, COUNT(*) AS TOTAL
FROM CTE 
GROUP BY SHIPPING_MODE )

SELECT SHIPPING_MODE, DELAYED_SHIPPING_MODE, TOTAL, ROUND((DELAYED_SHIPPING_MODE/TOTAL)*100,2) AS DELAYED_PERCENT
FROM TABLE_01
ORDER BY DELAYED_PERCENT DESC

/***************************************************************************************************
Question 4: Type have the most completed order rate*/ 

USE SUPPLY_DB;
WITH TABLE_02 AS (
SELECT TYPE, COUNT(CASE WHEN ORDER_STATUS = 'COMPLETE' THEN 'COMPLETED' END) AS COMPLETED_ORDER, COUNT(*) AS TOTAL_STATUS
FROM ORDERS
GROUP BY TYPE )

SELECT TYPE,  COMPLETED_ORDER,  TOTAL_STATUS, ROUND ((COMPLETED_ORDER/TOTAL_STATUS)*100,2) AS COMPLETED_ORDER_RATE 
FROM TABLE_02